### ISSUE TITLE
Update Unity Versions Crawler Due to Changes on Unity Archive Page

### ISSUE THREAD

**Issue by GabLeRoux** [game-ci/versioning-backend#48]
Due to [recent](https://github.com/game-ci/unity-builder/issues/652#issuecomment-2140039446) [changes](https://github.com/game-ci/unity-builder/issues/652#issuecomment-2140060063) in the Unity archive page format, our automated system for retrieving new Unity versions has been
unable to detect and publish the latest releases. This has caused delays in making new Unity versions available for the
community.

#### Affected Versions

All Unity versions published after May 16, 2024, including but not limited to:

- Unity 6000.0.3f1
- Unity 6000.0.4f1
- Unity 2022.3.30f1
- Unity 2022.3.31f1

#### Proposed Solution

* **Option 1**: We need to update our crawler to adapt to the new format of the Unity archive page.
* **Option 2**: We can consider switching to the Unity symbol server endpoints for metadata retrieval, which appear
  to have a more consistent format and are less likely to change.

Symbol Server Endpoints:

- [http://symbolserver.unity3d.com/000Admin/server.txt](http://symbolserver.unity3d.com/000Admin/server.txt)
- [http://symbolserver.unity3d.com/000Admin/history.txt](http://symbolserver.unity3d.com/000Admin/history.txt)

Both files seem to have the same modified date/time and may be used for scraping and parsing metadata.

#### How to Help

We welcome contributions from the community to help solve this issue. Here are some steps to get started:

1. Analyze the new format of the Unity archive page and the structure of the symbol server endpoints.
2. Update the crawler code to parse the new format or switch to the symbol server endpoints.
3. Test the updated crawler to ensure it correctly retrieves the latest Unity versions.
4. Submit a pull request with your changes.

#### Interim Solutions

While we work on resolving this issue, we recommend using the last images that were published to maintain your CI
workflows:

- Unity 6000.0.2f1
- Unity 2023.2.20f1
- Unity 2022.3.29f1
- Unity 2021.3.38f1

You can find the list of available versions [here](https://game.ci/docs/docker/versions).

### Technical details and files we might have to update

* [`functions/src/logic/ingestUnityVersions/scrapeVersions.ts`](https://github.com/game-ci/versioning-backend/blob/66b91e96cd232687a1ee9040345c49906966303b/functions/src/logic/ingestUnityVersions/scrapeVersions.ts)
  This file contains the logic for scraping versions from the Unity archive page. We might have to update this file to
  adapt to the new format of the archive page or switch to using the Unity symbol server endpoints.
* [`functions/src/logic/ingestRepoVersions/index.ts`](https://github.com/game-ci/versioning-backend/blob/66b91e96cd232687a1ee9040345c49906966303b/functions/src/logic/ingestRepoVersions/index.ts)
  This file initiates the scraping process and updates the database. We need to ensure it correctly handles any new data
  format.
* [`functions/src/cron/index.ts`](https://github.com/game-ci/versioning-backend/blob/66b91e96cd232687a1ee9040345c49906966303b/functions/src/cron/index.ts)
  This file schedules the routine tasks, including the ingestion of Unity versions. Ensure it calls the updated
  ingestion function.

**Comment by GabLeRoux** [comment]
Based on a quick chat in a private channel, the symbols endpoints might not be a very good option as we don't know where to retrieve the `changeset` information out of it.

The easiest option is to keep using the crawler:

* **Option 1**: We need to update our crawler to adapt to the new format of the Unity archive page.

**Comment by MrGadget1024** [comment]
Unless your crawler can click buttons to fire off JS functions to rebuild the DOM, you're done with that archive page.

What you could do is monitor the Symbol Server Endpoints for new versions to appear, then crawl the WhatsNew URL with the new version appended, e.g. https://unity.com/releases/editor/whats-new/major.minor.patch and crawl the packages for that version from that page.

The release notes are at the bottom:
- [https://unity.com/releases/editor/whats-new/6000.0.4](https://unity.com/releases/editor/whats-new/6000.0.4)

**Comment by webbertakken** [comment]
Possibly relevant for the future: https://github.com/mob-sakai/unity-changeset/issues/16

**Comment by AndrewKahr** [comment]
Actually this is probably relevant right now. The scrapper is broken again as of a few days ago because Unity changed their archive site again. We will likely want to move to the GraphQL strategy to restore functionality. I think we should reopen this ticket.

**Comment by webbertakken** [comment]
There's already a working [implementation](https://github.com/mob-sakai/unity-changeset/blob/main/src/unityGraphQL.ts) of getting the info from the GraphQL API.

For our use-case we might need to make sure that the initial call (which isn't cached on Unity Technologies side) doesn't take too long for our 30 second window in which the scheduler runs.

**Comment by PitouGames** [comment]
Do you have a way to provide the version and hash (= the download link) manually in the system to trigger images build?
If no, I think you really need to have this too. With a way to manually short circuit the failing scrapping due to Unity changes, it will still be possible to build and release images (with just a little human intervention).
If yes, why not use it right now for 2022.3.52f1? 😉

**Comment by webbertakken** [comment]
This automated system has worked flawlessly for 5+ years, until we had a couple of hiccups that weren't caused by ourselves in the past few months.

I prefer simply fixing hiccup in the automated system over introducing manual work intentionally. Just need someone to make the actual changes.

**Comment by PitouGames** [comment]
Thank you for the fix @AndrewKahr !

There is still a small issue: version 2021.3.46f1 hasn't been built... (It may be the last 2021 version)

**Comment by MrGadget1024** [comment]
> Thank you for the fix @AndrewKahr !
> 
> There is still a small issue: version 2021.3.46f1 hasn't been built... (It may be the last 2021 version)

That version just dropped Nov 13 2024, but may be buggered...

![image](https://github.com/user-attachments/assets/9c2d2845-6591-4415-88f1-a06e596a1bd0)

**Comment by PitouGames** [comment]
Manual download is working well here: https://unity.com/fr/releases/editor/whats-new/2021.3.46#installs
I was able to build the images last sunday: https://hub.docker.com/r/pitougames/unityci-editor/tags?name=2021.3.46
